### ISSUE TITLE
This maybe a bug

### ISSUE THREAD

**Issue by bobchenlut** [yl-1993/Matrix-Capsules-EM-PyTorch#8]
In "add_coord(self, v, b, h, w, B, C, psize):" function, 
>coor = 1. * torch.arange(h) / h

always ouput zeros,and I think that should be changed as 

>coor = torch.arange(h).float()/h
.

**Comment by yl-1993** [comment]
@bobchenlut It works well under `0.4.0` and the version below.
The default type of `torch.arange` has been changed to `LongTensor` since `0.4.1` . ( see https://github.com/pytorch/pytorch/issues/2812 and https://github.com/pytorch/pytorch/issues/11511 for more discussions.)

I have modified the code to support this. Thanks for pointing out!
